server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: 'http://localhost:8082'
          predicates:
            - Path=/api/v1/**
        - id: order-service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/v1/**