server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**